Repository BlueMoon-Labs/Redmoon-Keep, pull requests merged in 2025-03, with the labels that each got.

#79 Скомкольца модулярные - порт с Azure Peak
  modular_redmoon/modules/scomrings/rings/misc.dmi
  modular_redmoon/modules/scomrings/rings/scomm.dm
  modular_redmoon/modules/scomrings/rings/startthings.dm
  modular_redmoon/modules/scomrings/rings/storage.dm
  modular_redmoon/modules/scomrings/rings/trade.dm
  modular_redmoon/modules/scomrings/ringssound/garrisonscom.ogg
  roguetown.dme
Labels: Balance

#81 Починка рунлоков и добавление крафта.(МОДУЛЯРНО!!!!!!!)
  code/modules/jobs/job_types/roguetown/inquisition/puritan.dm
  modular_redmoon/modules/artificerandguns/runelock.dm
  modular_redmoon/modules/artificerandguns/runelock.dmi
  modular_redmoon/modules/artificerandguns/runelockrecpies.dm
  roguetown.dme
Labels: Balance

#96 Бафф New Moon Spellblade
  code/modules/jobs/job_types/roguetown/mercenaries/types/newmoon.dm
Labels: Balance

#30 Фикс экономики, первая попытка
  code/_onclick/item_attack.dm
  code/game/objects/structures/roguetown/rogueflora.dm
  code/game/turfs/closed/minerals.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  code/modules/roguetown/roguejobs/fisher/rod.dm
  code/modules/roguetown/roguejobs/tailor/tanning.dm
  code/modules/roguetown/roguestock/stockpile.dm
  modular_redmoon/modules/economy_fixes/items_informative_desc.dm
  modular_redmoon/modules/economy_fixes/items_prices.dm
  modular_redmoon/modules/economy_fixes/mobs_loot.dm
  modular_redmoon/modules/economy_fixes/sewing.dm
  modular_redmoon/modules/economy_fixes/shipping.dm
  modular_redmoon/modules/economy_fixes/smithing.dm
  modular_redmoon/modules/economy_fixes/stockpile.dm
  modular_redmoon/modules/economy_fixes/tailoring.dm
  modular_redmoon/modules/economy_fixes/towners_should_work_in_bog.dm
  modular_redmoon/modules/jobs/job_types/roguetown/goblin/goblinrabble.dm
  modular_redmoon/modules/jobs/job_types/roguetown/goblin/goblinsmith.dm
  roguetown.dme
Labels: Mapping

#102 Починка и обновление кафтана.
  icons/roguetown/clothing/onmob/helpers/sleeves_shirts.dmi
  modular_redmoon/code/modules/clothing/rogueclothes/shirts.dm
  modular_redmoon/icons/shirts_onmob.dmi
Labels: Spriting

#108 desert_rider_classes_rebalance
  code/modules/jobs/job_types/roguetown/mercenaries/types/desertrider.dm
Labels: Balance

#111 Desert rider bladecaster rebalance
  code/modules/jobs/job_types/roguetown/mercenaries/types/desertrider.dm
Labels: Balance

#113 blade_dancer_stats_balance
  code/modules/jobs/job_types/roguetown/mercenaries/types/desertrider.dm
Labels: Balance

#115 duchess_swords
  code/modules/jobs/job_types/roguetown/nobility/ruler.dm
Labels: Balance

#117 Обновление мэра
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
  code/modules/mob/living/carbon/human/examine.dm
  modular_redmoon/modules/jobs/job_types/roguetown/garrison/mayor.dm
Labels: Balance
